# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  releasebot
  labels:
    app:  releasebot
spec:
  selector:
    matchLabels:
      app: releasebot
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  releasebot
    spec:
      containers:
      - name:  releasebot
        image:  clanktron/releasebot:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: slack_token
          valueFrom:
            secretKeyRef:
              name: releasebot-secret-env 
              key: slack_token
        - name: slack_channel
          valueFrom:
            secretKeyRef:
              name: releasebot-secret-env 
              key: slack_channel
        - name: github_token
          valueFrom:
            secretKeyRef:
              name: releasebot-secret-env
              key: github_token
        - name: releasebot_config
          valueFrom:
            configMapKeyRef:
              name: releasebot-env
              key: releasebot_config
        volumeMounts:
        - name: repos
          mountPath: /app/config.json
          subPath: config.json
      volumes:
        - name: repos
          configMap:
            name: releasebot
      restartPolicy: Always
---

